export const GET_POPULAR_HOME_LIST_REQUESTED =
  'views/PopularHome/GET_POPULAR_HOME_LIST_REQUESTED';
export const GET_POPULAR_HOME_LIST_SUCCESS =
  'views/PopularHome/GET_POPULAR_HOME_LIST_SUCCESS';
export const GET_POPULAR_HOME_LIST_FAILED =
  'views/PopularHome/GET_POPULAR_HOME_LIST_FAILED';

export const GET_ECONOMY_NEWS_LIST_REQUESTED =
  'views/PopularHome/GET_ECONOMY_NEWS_LIST_REQUESTED';
export const GET_ECONOMY_NEWS_LIST_SUCCESS =
  'views/PopularHome/GET_ECONOMY_NEWS_LIST_SUCCESS';
export const GET_ECONOMY_NEWS_LIST_FAILED =
  'views/PopularHome/GET_ECONOMY_NEWS_LIST_FAILED';

export const GET_POLITICS_NEWS_LIST_REQUESTED =
  'views/PopularHome/GET_POLITICS_NEWS_LIST_REQUESTED';
export const GET_POLITICS_NEWS_LIST_SUCCESS =
  'views/PopularHome/GET_POLITICS_NEWS_LIST_SUCCESS';
export const GET_POLITICS_NEWS_LIST_FAILED =
  'views/PopularHome/GET_POLITICS_NEWS_LIST_FAILED';

export const GET_CATEGORY_NEWS_LIST_REQUESTED =
  'views/PopularHome/GET_CATEGORY_NEWS_LIST_REQUESTED';
export const GET_CATEGORY_NEWS_LIST_SUCCESS =
  'views/PopularHome/GET_CATEGORY_NEWS_LIST_SUCCESS';
export const GET_CATEGORY_NEWS_LIST_FAILED =
  'views/PopularHome/GET_CATEGORY_NEWS_LIST_FAILED';
  
export const GET_SOURCE_NEWS_LIST_REQUESTED =
  'views/PopularHome/GET_SOURCE_NEWS_LIST_REQUESTED';
export const GET_SOURCE_NEWS_LIST_SUCCESS =
  'views/PopularHome/GET_SOURCE_NEWS_LIST_SUCCESS';
export const GET_SOURCE_NEWS_LIST_FAILED =
  'views/PopularHome/GET_SOURCE_NEWS_LIST_FAILED';
