export const ENDPOINT = {
  TOPHEADLINES: '/top-headlines',
  EVERYTHING:'everything',
  HOMEJSON: '/home.json',
  ARTSJSON: '/arts.json',
  SCIENCEJSON: '/science.json',
  WORLDJSON: '/world.json',
  THEGUARDIAN: '/search',
  GUARDIANECONOMY:'search?q=economy',
  GUARDIANPOLITICS:'search?q=politics',
  LOGIN:'login',
  REGISTER:'register',
  PREFERENCE:'preference',
  LOGOUT:'logout',
};