export const LOGOUT = 'app/LOGOUT';
export const AUTHENTICATED = 'app/AUTHENTICATED';
export const CLOSE_SIDE_NAV = 'app/CLOSE_SIDE_NAV';


export const PREFERENCE_REQUESTED =
  'app/PREFERENCE_REQUESTED';
export const PREFERENCE_SUCCESS =
  'app/PREFERENCE_SUCCESS';
export const PREFERENCE_FAILED =
  'app/PREFERENCE_FAILED';

