export const GET_TRENDING_HOME_LIST_REQUESTED =
  "views/TrendingHome/GET_TRENDING_HOME_LIST_REQUESTED"
export const GET_TRENDING_HOME_LIST_SUCCESS =
  "views/TrendingHome/GET_TRENDING_HOME_LIST_SUCCESS"
export const GET_TRENDING_HOME_LIST_FAILED =
  "views/TrendingHome/GET_TRENDING_HOME_LIST_FAILED"

export const GET_ART_NEWS_LIST_REQUESTED =
  "views/TrendingHome/GET_ART_NEWS_LIST_REQUESTED"
export const GET_ART_NEWS_LIST_SUCCESS =
  "views/TrendingHome/GET_ART_NEWS_LIST_SUCCESS"
export const GET_ART_NEWS_LIST_FAILED =
  "views/TrendingHome/GET_ART_NEWS_LIST_FAILED"

export const GET_SCIENCE_NEWS_LIST_REQUESTED =
  "views/TrendingHome/GET_SCIENCE_NEWS_LIST_REQUESTED"
export const GET_SCIENCE_NEWS_LIST_SUCCESS =
  "views/TrendingHome/GET_SCIENCE_NEWS_LIST_SUCCESS"
export const GET_SCIENCE_NEWS_LIST_FAILED =
  "views/TrendingHome/GET_SCIENCE_NEWS_LIST_FAILED"

export const GET_WORLD_NEWS_LIST_REQUESTED =
  "views/TrendingHome/GET_WORLD_NEWS_LIST_REQUESTED"
export const GET_WORLD_NEWS_LIST_SUCCESS =
  "views/TrendingHome/GET_WORLD_NEWS_LIST_SUCCESS"
export const GET_WORLD_NEWS_LIST_FAILED =
  "views/TrendingHome/GET_WORLD_NEWS_LIST_FAILED"