export const GET_TOP_HOME_LIST_REQUESTED =
  'views/TopHome/GET_TOP_HOME_LIST_REQUESTED';
export const GET_TOP_HOME_LIST_SUCCESS =
  'views/TopHome/GET_TOP_HOME_LIST_SUCCESS';
export const GET_TOP_HOME_LIST_FAILED =
  'views/TopHome/GET_TOP_HOME_LIST_FAILED';

  export const GET_TOP_HOME_CATEGORY_REQUESTED =
  'views/TopHome/GET_TOP_HOME_CATEGORY_REQUESTED';
export const GET_TOP_HOME_SOURCE_SUCCESS =
  'views/TopHome/GET_TOP_HOME_SOURCE_SUCCESS';
export const GET_TOP_HOME_CATEGORY_SUCCESS =
  'views/TopHome/GET_TOP_HOME_CATEGORY_SUCCESS';
export const GET_TOP_HOME_CATEGORY_FAILED =
  'views/TopHome/GET_TOP_HOME_CATEGORY_FAILED';